# Generated by Django 5.1.7 on 2025-03-11 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0002_alter_tourtype_type_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название тура')),
                ('description', models.TextField(verbose_name='Описание тура')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('duration', models.CharField(help_text='Например: 3 дня, 5 часов', max_length=100, verbose_name='Продолжительность')),
                ('start_location', models.CharField(max_length=255, verbose_name='Место начала тура')),
                ('image', models.TextField(blank=True, null=True, verbose_name='Изображение в Base64')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('tour_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tours', to='main.tourtype', verbose_name='Тип тура')),
            ],
        ),
    ]
