# Generated by Django 5.1.7 on 2025-03-11 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourtype',
            name='type_img',
            field=models.ImageField(blank=True, null=True, upload_to='tour_types/', verbose_name='Изображение типа тура'),
        ),
    ]
