# Generated by Django 5.1.7 on 2025-03-10 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок страницы')),
                ('introduction', models.TextField(verbose_name='Вступление')),
                ('history', models.TextField(verbose_name='История компании')),
                ('mission', models.TextField(verbose_name='Миссия')),
                ('meta_title', models.CharField(blank=True, max_length=200, verbose_name='Мета-заголовок')),
                ('meta_description', models.TextField(blank=True, verbose_name='Мета-описание')),
            ],
            options={
                'verbose_name': 'Страница О нас',
                'verbose_name_plural': 'Страница О нас',
            },
        ),
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50, verbose_name='Число (например, 150+)')),
                ('description', models.CharField(max_length=200, verbose_name='Описание')),
                ('about_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='about.aboutpage')),
            ],
            options={
                'verbose_name': 'Достижение',
                'verbose_name_plural': 'Достижения',
            },
        ),
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('address', models.CharField(max_length=200, verbose_name='Адрес')),
                ('facebook_url', models.URLField(blank=True, verbose_name='Facebook')),
                ('twitter_url', models.URLField(blank=True, verbose_name='Twitter')),
                ('whatsapp_url', models.URLField(blank=True, verbose_name='WhatsApp')),
                ('instagram_url', models.URLField(blank=True, verbose_name='Instagram')),
                ('about_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_info', to='about.aboutpage')),
            ],
            options={
                'verbose_name': 'Контактная информация',
                'verbose_name_plural': 'Контактная информация',
            },
        ),
        migrations.CreateModel(
            name='GalleryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='gallery/', verbose_name='Фото')),
                ('video_url', models.URLField(blank=True, verbose_name='Ссылка на видео')),
                ('about_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_items', to='about.aboutpage')),
            ],
            options={
                'verbose_name': 'Элемент галереи',
                'verbose_name_plural': 'Элементы галереи',
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('role', models.CharField(max_length=100, verbose_name='Должность')),
                ('description', models.TextField(verbose_name='Описание')),
                ('photo', models.ImageField(blank=True, upload_to='team_photos/', verbose_name='Фото')),
                ('about_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_members', to='about.aboutpage')),
            ],
            options={
                'verbose_name': 'Член команды',
                'verbose_name_plural': 'Члены команды',
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя клиента')),
                ('text', models.TextField(verbose_name='Текст отзыва')),
                ('photo', models.ImageField(blank=True, upload_to='testimonials/', verbose_name='Фото клиента')),
                ('about_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testimonials', to='about.aboutpage')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
        migrations.CreateModel(
            name='Value',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название ценности')),
                ('description', models.TextField(verbose_name='Описание ценности')),
                ('about_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='about.aboutpage')),
            ],
            options={
                'verbose_name': 'Ценность',
                'verbose_name_plural': 'Ценности',
            },
        ),
    ]
